title: IT-блог
description: > # this means to ignore newlines until "baseurl:"
  Blog with theme Future Imperfect<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Yujung2Lee.github.io" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'Yujung2Lee'
  last_name: 'Yujung2Lee'
  avatar: '/images/avatar.jpeg'
  github_username:  Yujung2Lee
  email: vika@kaptn.ru
  vk_id: id201664979
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


